"""
Numba JIT kernel for the closed-loop SME trajectory (Section IV-H).

This module is a *compiled re-implementation* of the per-step mathematics in
``coefficients.py``, ``integrator.py``, ``controller.py`` and the loop body of
``simulate.run_trajectory``.  The original pure-Python modules are retained
unchanged and remain the validated reference (their unit tests are untouched);
``simulate.run_trajectory`` cross-checks this kernel against them.

Design notes
------------
* All System operator data is passed as plain contiguous ``complex128`` arrays
  (generators stacked to ``(NG,N,N)``; coherent/dissipative jump operators to
  ``(m,N,N)`` / ``(p,N,N)``).  Daggers and ``J^dag J`` products are precomputed
  on the Python side so the inner loop holds no allocations beyond small work
  matrices.
* The controller coefficients are evaluated on the *design* operator set while
  the state is propagated by the *plant* operator set, exactly mirroring the
  ``design_sys`` semantics of the reference loop (robust/mismatched studies).
  When ``design_sys is None`` the two sets are the same arrays.
* The seeded Wiener increments are generated by numpy on the Python side and
  passed in as ``dW``; the kernel draws no random numbers.  This reproduces the
  reference trajectories bit-for-bit under a given seed and sidesteps Numba RNG.
* ``fastmath`` is left at its default (off): float64 IEEE arithmetic, so seeded
  figures reproduce to ~1 ulp.  ``cache=True`` lets the ten worker processes of
  the ``*_acc`` drivers load the compiled kernel instead of each recompiling.

Case codes (translated back to the reference strings by the wrapper):
    -1 -> "V"   (dormant)        1 -> "I"   2 -> "II"   3 -> "III"   4 -> "IV"
multichannel non-dormant returns the saturated-channel count n (0 -> "I",
n>0 -> "sat(n)").
"""
from __future__ import annotations
import numpy as np

try:
    from numba import njit
    HAVE_NUMBA = True
except Exception:                                    # pragma: no cover
    HAVE_NUMBA = False

    def njit(*args, **kwargs):                        # no-op fallback decorator
        if len(args) == 1 and callable(args[0]):
            return args[0]

        def _wrap(f):
            return f
        return _wrap


# ==========================================================================
# Dense complex primitives (explicit loops: fastest for N = 2, 4)
# ==========================================================================
@njit(cache=True)
def _mm(A, B):
    """Complex matrix product A @ B for small square A, B."""
    N = A.shape[0]
    C = np.zeros((N, N), np.complex128)
    for i in range(N):
        for k in range(N):
            a = A[i, k]
            if a != 0.0:
                for j in range(N):
                    C[i, j] += a * B[k, j]
    return C


@njit(cache=True)
def _from_bloch(x, G, I_over_N, N, NG):
    """rho = I/N + sum_k x_k T_k."""
    rho = np.empty((N, N), np.complex128)
    for i in range(N):
        for j in range(N):
            rho[i, j] = I_over_N[i, j]
    for k in range(NG):
        xk = x[k]
        for i in range(N):
            for j in range(N):
                rho[i, j] += xk * G[k, i, j]
    return rho


@njit(cache=True)
def _project(X, G, N, NG):
    """Generator coordinates of a Hermitian operator: x_k = 2 Re Tr(T_k X)."""
    out = np.empty(NG, np.float64)
    for k in range(NG):
        s = 0.0 + 0.0j
        for i in range(N):
            for j in range(N):
                s += G[k, i, j] * X[j, i]            # Tr(T_k X) = sum_ij T[i,j] X[j,i]
        out[k] = 2.0 * s.real
    return out


@njit(cache=True)
def _lindblad(J, Jd, JdJ, rho):
    """Dissipator D[J] rho = J rho J^dag - 1/2 {J^dag J, rho}."""
    JrJd = _mm(_mm(J, rho), Jd)
    a = _mm(JdJ, rho)
    b = _mm(rho, JdJ)
    N = rho.shape[0]
    out = np.empty((N, N), np.complex128)
    for i in range(N):
        for j in range(N):
            out[i, j] = JrJd[i, j] - 0.5 * (a[i, j] + b[i, j])
    return out


@njit(cache=True)
def _innovation(L, Ld, rho):
    """Measurement superoperator H[L] rho = L rho + rho L^dag - Tr(.) rho."""
    A = np.empty(rho.shape, np.complex128)
    LR = _mm(L, rho)
    RLd = _mm(rho, Ld)
    N = rho.shape[0]
    trA = 0.0 + 0.0j
    for i in range(N):
        for j in range(N):
            A[i, j] = LR[i, j] + RLd[i, j]
        trA += A[i, i]
    out = np.empty((N, N), np.complex128)
    for i in range(N):
        for j in range(N):
            out[i, j] = A[i, j] - trA * rho[i, j]
    return out


# ==========================================================================
# Coefficients (trace formulas 7-10), design operator set
# ==========================================================================
@njit(cache=True)
def _coeffs(rho, Pi, H0, L, Ld, LdL, Hc, Lc, Lcd, LcdLc, eta,
            N, m, p, betaH_out, betaD_out):
    """Fill betaH_out (m), betaD_out (p); return (mu, sigma)."""
    # mu = -Re Tr( Pi (-i[H0,rho] + D[L]rho) )
    commH0 = _mm(H0, rho)
    tmp = _mm(rho, H0)
    DL = _lindblad(L, Ld, LdL, rho)
    M = np.empty((N, N), np.complex128)
    for i in range(N):
        for j in range(N):
            M[i, j] = -1j * (commH0[i, j] - tmp[i, j]) + DL[i, j]
    PiM = _mm(Pi, M)
    mu = 0.0
    for i in range(N):
        mu -= PiM[i, i].real

    # betaH_i = Re( i Tr( (rho Pi - Pi rho) Hc_i ) )
    rPi = _mm(rho, Pi)
    Pir = _mm(Pi, rho)
    comm = np.empty((N, N), np.complex128)
    for i in range(N):
        for j in range(N):
            comm[i, j] = rPi[i, j] - Pir[i, j]
    for c in range(m):
        T = _mm(comm, Hc[c])
        tr = 0.0 + 0.0j
        for i in range(N):
            tr += T[i, i]
        betaH_out[c] = (1j * tr).real

    # betaD_j = -Re Tr( Pi D[Lc_j] rho )
    for c in range(p):
        Dj = _lindblad(Lc[c], Lcd[c], LcdLc[c], rho)
        T = _mm(Pi, Dj)
        tr = 0.0
        for i in range(N):
            tr += T[i, i].real
        betaD_out[c] = -tr

    # sigma = -sqrt(eta) Re Tr( Pi H[L] rho )
    HL = _innovation(L, Ld, rho)
    T = _mm(Pi, HL)
    tr = 0.0
    for i in range(N):
        tr += T[i, i].real
    sigma = -np.sqrt(eta) * tr
    return mu, sigma


# ==========================================================================
# Drift / diffusion / Milstein on the plant operator set
# ==========================================================================
@njit(cache=True)
def _drift(x, u, gamma, G, I_over_N, H0, L, Ld, LdL,
           Hc, Lc, Lcd, LcdLc, N, NG, m, p):
    rho = _from_bloch(x, G, I_over_N, N, NG)
    H = np.empty((N, N), np.complex128)
    for i in range(N):
        for j in range(N):
            H[i, j] = H0[i, j]
    for c in range(m):
        uc = u[c]
        for i in range(N):
            for j in range(N):
                H[i, j] += uc * Hc[c, i, j]
    HR = _mm(H, rho)
    RH = _mm(rho, H)
    DL = _lindblad(L, Ld, LdL, rho)
    drho = np.empty((N, N), np.complex128)
    for i in range(N):
        for j in range(N):
            drho[i, j] = -1j * (HR[i, j] - RH[i, j]) + DL[i, j]
    for c in range(p):
        gc = gamma[c]
        if gc != 0.0:
            Dc = _lindblad(Lc[c], Lcd[c], LcdLc[c], rho)
            for i in range(N):
                for j in range(N):
                    drho[i, j] += gc * Dc[i, j]
    return _project(drho, G, N, NG)


@njit(cache=True)
def _diffusion(x, G, I_over_N, L, Ld, eta, N, NG):
    rho = _from_bloch(x, G, I_over_N, N, NG)
    inn = _innovation(L, Ld, rho)
    pr = _project(inn, G, N, NG)
    se = np.sqrt(eta)
    out = np.empty(NG, np.float64)
    for k in range(NG):
        out[k] = se * pr[k]
    return out


@njit(cache=True)
def _milstein_corr(x, G, I_over_N, L, Ld, eta, N, NG, eps):
    Gd = _diffusion(x, G, I_over_N, L, Ld, eta, N, NG)
    xp = np.empty(NG, np.float64)
    xm = np.empty(NG, np.float64)
    for k in range(NG):
        xp[k] = x[k] + eps * Gd[k]
        xm[k] = x[k] - eps * Gd[k]
    Gp = _diffusion(xp, G, I_over_N, L, Ld, eta, N, NG)
    Gm = _diffusion(xm, G, I_over_N, L, Ld, eta, N, NG)
    out = np.empty(NG, np.float64)
    for k in range(NG):
        out[k] = (Gp[k] - Gm[k]) / (2.0 * eps)
    return out


@njit(cache=True)
def _project_physical(x, G, I_over_N, N, NG):
    """Clip negative eigenvalues, renormalise trace; return (x', neg)."""
    rho = _from_bloch(x, G, I_over_N, N, NG)
    rh = np.empty((N, N), np.complex128)
    for i in range(N):
        for j in range(N):
            rh[i, j] = 0.5 * (rho[i, j] + np.conj(rho[j, i]))
    w, V = np.linalg.eigh(rh)
    wmin = w[0]
    for a in range(1, N):
        if w[a] < wmin:
            wmin = w[a]
    neg = -wmin if wmin < 0.0 else 0.0
    trr = 0.0
    for i in range(N):
        trr += rh[i, i].real
    if neg == 0.0 and abs(trr - 1.0) < 1e-12:
        return x, 0.0
    s = 0.0
    for a in range(N):
        if w[a] < 0.0:
            w[a] = 0.0
        s += w[a]
    rho_p = np.zeros((N, N), np.complex128)
    if s <= 0.0:
        for i in range(N):
            rho_p[i, i] = 1.0 / N
    else:
        for a in range(N):
            wa = w[a] / s
            for i in range(N):
                vi = V[i, a]
                for j in range(N):
                    rho_p[i, j] += wa * vi * np.conj(V[j, a])
    return _project(rho_p, G, N, NG), neg


# ==========================================================================
# QP solvers (write primal into u_cur, g_cur; return delta, nu, case-code)
# ==========================================================================
@njit(cache=True)
def _solve_closed_form(u_cur, g_cur, alpha, bH, bD, V, lam, u_prev,
                       wu, wr, wg, wd, umax, gmax):
    lamV = lam * V
    w_eq = wu + wr
    hist = wr * u_prev / w_eq
    Theta = alpha + bH * hist + lamV
    if Theta <= 0.0:
        u_cur[0] = hist
        g_cur[0] = 0.0
        return 0.0, 0.0, -1
    D_I = bH * bH / w_eq + bD * bD / wg + 1.0 / wd
    nu_I = Theta / D_I
    u_I = (wr * u_prev - nu_I * bH) / w_eq
    g_I = -nu_I * bD / wg
    u_ok = abs(u_I) <= umax
    g_ok = g_I <= gmax
    if u_ok and g_ok:
        u_cur[0] = u_I
        g_cur[0] = g_I
        return nu_I / wd, nu_I, 1
    if (not u_ok) and g_ok:
        usat = umax if u_I > 0.0 else (-umax if u_I < 0.0 else 0.0)
        N_II = alpha + bH * usat + lamV
        D_II = bD * bD / wg + 1.0 / wd
        nu_II = N_II / D_II
        g_II = -nu_II * bD / wg
        if g_II <= gmax:
            u_cur[0] = usat
            g_cur[0] = g_II
            return nu_II / wd, nu_II, 2
        N_IV = alpha + bH * usat + bD * gmax + lamV
        nu_IV = N_IV * wd
        u_cur[0] = usat
        g_cur[0] = gmax
        return nu_IV / wd, nu_IV, 4
    if u_ok and (not g_ok):
        N_III = alpha + bH * hist + bD * gmax + lamV
        D_III = bH * bH / w_eq + 1.0 / wd
        nu_III = N_III / D_III
        u_III = (wr * u_prev - nu_III * bH) / w_eq
        if abs(u_III) <= umax:
            u_cur[0] = u_III
            g_cur[0] = gmax
            return nu_III / wd, nu_III, 3
        usat = umax if u_III > 0.0 else (-umax if u_III < 0.0 else 0.0)
        N_IV = alpha + bH * usat + bD * gmax + lamV
        nu_IV = N_IV * wd
        u_cur[0] = usat
        g_cur[0] = gmax
        return nu_IV / wd, nu_IV, 4
    usat = umax if u_I > 0.0 else (-umax if u_I < 0.0 else 0.0)
    N_IV = alpha + bH * usat + bD * gmax + lamV
    nu_IV = N_IV * wd
    u_cur[0] = usat
    g_cur[0] = gmax
    return nu_IV / wd, nu_IV, 4


@njit(cache=True)
def _primal_resid(nu, alpha, betaH, betaD, V, lam, u_prev, wu, wr,
                  wgamma, wdelta, umax, gmax, m, p, u_out, g_out):
    """Box-projected stationary primal at nu; return (delta, residual)."""
    delta = nu / wdelta
    sumH = 0.0
    for i in range(m):
        w_eq = wu[i] + wr[i]
        ui = (wr[i] * u_prev[i] - nu * betaH[i]) / w_eq
        if ui < -umax[i]:
            ui = -umax[i]
        elif ui > umax[i]:
            ui = umax[i]
        u_out[i] = ui
        sumH += betaH[i] * ui
    sumD = 0.0
    for j in range(p):
        gj = -nu * betaD[j] / wgamma[j]
        if gj < 0.0:
            gj = 0.0
        elif gj > gmax[j]:
            gj = gmax[j]
        g_out[j] = gj
        sumD += betaD[j] * gj
    res = alpha + sumH + sumD + lam * V - delta
    return delta, res


@njit(cache=True)
def _solve_multichannel(u_cur, g_cur, alpha, betaH, betaD, V, lam, u_prev,
                        wu, wr, wgamma, wdelta, umax, gmax, m, p, tol):
    delta0, g0 = _primal_resid(0.0, alpha, betaH, betaD, V, lam, u_prev,
                               wu, wr, wgamma, wdelta, umax, gmax, m, p,
                               u_cur, g_cur)
    if g0 <= 0.0:
        return 0.0, 0.0, -1                          # dormant; primal at nu=0
    nu_hi = 1.0
    for _ in range(200):
        d, r = _primal_resid(nu_hi, alpha, betaH, betaD, V, lam, u_prev,
                             wu, wr, wgamma, wdelta, umax, gmax, m, p,
                             u_cur, g_cur)
        if r < 0.0:
            break
        nu_hi *= 2.0
    lo = 0.0
    hi = nu_hi
    for _ in range(200):
        mid = 0.5 * (lo + hi)
        d, r = _primal_resid(mid, alpha, betaH, betaD, V, lam, u_prev,
                             wu, wr, wgamma, wdelta, umax, gmax, m, p,
                             u_cur, g_cur)
        if r > 0.0:
            lo = mid
        else:
            hi = mid
        if hi - lo < tol:
            break
    nu = 0.5 * (lo + hi)
    delta, r = _primal_resid(nu, alpha, betaH, betaD, V, lam, u_prev,
                             wu, wr, wgamma, wdelta, umax, gmax, m, p,
                             u_cur, g_cur)
    nsat = 0
    for i in range(m):
        if abs(abs(u_cur[i]) - umax[i]) < 1e-9:
            nsat += 1
    for j in range(p):
        if abs(g_cur[j] - gmax[j]) < 1e-9:
            nsat += 1
    return delta, nu, nsat


# ==========================================================================
# Full trajectory kernel
# ==========================================================================
@njit(cache=True)
def run_traj_kernel(
    x0, dW, params, ints,
    # plant operator set
    G, I_over_N, Pi_p, H0_p, L_p, Ld_p, LdL_p, Hc_p, Lc_p, Lcd_p, LcdLc_p,
    # design (controller) operator set
    Pi_c, H0_c, L_c, Ld_c, LdL_c, Hc_c, Lc_c, Lcd_c, LcdLc_c,
    # outputs
    xi_o, eps_o, epssb_o, u_o, g_o, delta_o, nu_o, bH_o, bD_o, alpha_o, case_o,
):
    dt = params[0]
    eta_p = params[1]
    eta_c = params[2]
    eps0 = params[3]
    eps_T = params[4]
    rfun = params[5]
    s_bar = params[6]
    s_b = params[7]
    lam = params[8]
    cc = params[9]
    eps_f = params[10]
    wr_const = params[11]
    umax = params[12]
    gmax = params[13]
    tol = params[14]
    eps_mil = params[15]
    wgamma = params[16]
    wdelta = params[17]

    n_steps = ints[0]
    N = ints[1]
    NG = ints[2]
    m = ints[3]
    p = ints[4]
    single = ints[5]
    project = ints[6]
    regularized = ints[7]

    x = x0.copy()
    u_prev = np.zeros(m, np.float64)
    u_cur = np.zeros(m, np.float64)
    g_cur = np.zeros(p, np.float64)
    betaH = np.zeros(m, np.float64)
    betaD = np.zeros(p, np.float64)
    wu = np.zeros(m, np.float64)
    wr = np.zeros(m, np.float64)
    umax_v = np.empty(m, np.float64)
    gmax_v = np.empty(p, np.float64)
    wgamma_v = np.empty(p, np.float64)
    for i in range(m):
        umax_v[i] = umax
    for j in range(p):
        gmax_v[j] = gmax
        wgamma_v[j] = wgamma

    max_neg = 0.0
    confined = 1

    for n in range(n_steps):
        t = n * dt
        rho = _from_bloch(x, G, I_over_N, N, NG)

        # physicality monitor on the (unprojected) plant state
        rh = np.empty((N, N), np.complex128)
        for i in range(N):
            for j in range(N):
                rh[i, j] = 0.5 * (rho[i, j] + np.conj(rho[j, i]))
        ev = np.linalg.eigvalsh(rh)
        evmin = ev[0]
        for a in range(1, N):
            if ev[a] < evmin:
                evmin = ev[a]
        if -evmin > max_neg:
            max_neg = -evmin

        # infidelity (plant target)
        trPiR = 0.0
        PiR = _mm(Pi_p, rho)
        for i in range(N):
            trPiR += PiR[i, i].real
        xi = 1.0 - trPiR

        expn = np.exp(-rfun * t)
        eps_t = eps_T + (eps0 - eps_T) * expn
        eps_dot = -rfun * (eps0 - eps_T) * expn
        if xi >= eps_t:
            confined = 0
        s = eps_t - xi
        if s < s_b:
            s = s_b
        V = -np.log(s / s_bar)
        kappa_V = 1.0 / s

        # controller coefficients on the design operator set, plant rho
        mu, sigma = _coeffs(rho, Pi_c, H0_c, L_c, Ld_c, LdL_c,
                            Hc_c, Lc_c, Lcd_c, LcdLc_c, eta_c,
                            N, m, p, betaH, betaD)
        alpha = mu - eps_dot + 0.5 * kappa_V * sigma * sigma

        for i in range(m):
            if regularized:
                wu[i] = cc / (abs(betaH[i]) + eps_f)
                wr[i] = wr_const
            else:
                wu[i] = 1.0
                wr[i] = 0.0

        if single:
            delta, nu, code = _solve_closed_form(
                u_cur, g_cur, alpha, betaH[0], betaD[0], V, lam, u_prev[0],
                wu[0], wr[0], wgamma, wdelta, umax, gmax)
        else:
            delta, nu, code = _solve_multichannel(
                u_cur, g_cur, alpha, betaH, betaD, V, lam, u_prev,
                wu, wr, wgamma_v, wdelta, umax_v, gmax_v, m, p, tol)

        # record
        xi_o[n] = xi
        eps_o[n] = eps_t
        epssb_o[n] = eps_t - s_b
        delta_o[n] = delta
        nu_o[n] = nu
        alpha_o[n] = alpha
        case_o[n] = code
        for i in range(m):
            u_o[n, i] = u_cur[i]
            bH_o[n, i] = betaH[i]
        for j in range(p):
            g_o[n, j] = g_cur[j]
            bD_o[n, j] = betaD[j]

        # Milstein propagation on the plant
        F = _drift(x, u_cur, g_cur, G, I_over_N, H0_p, L_p, Ld_p, LdL_p,
                   Hc_p, Lc_p, Lcd_p, LcdLc_p, N, NG, m, p)
        Gv = _diffusion(x, G, I_over_N, L_p, Ld_p, eta_p, N, NG)
        GgG = _milstein_corr(x, G, I_over_N, L_p, Ld_p, eta_p, N, NG, eps_mil)
        dWn = dW[n]
        coef = 0.5 * (dWn * dWn - dt)
        xnew = np.empty(NG, np.float64)
        for k in range(NG):
            xnew[k] = x[k] + F[k] * dt + Gv[k] * dWn + coef * GgG[k]
        x = xnew

        if project:
            x, neg = _project_physical(x, G, I_over_N, N, NG)
            if neg > max_neg:
                max_neg = neg

        for i in range(m):
            u_prev[i] = u_cur[i]

    return max_neg, confined
